# Site settings
baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Caprica planet"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Your description"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "your@email.com"


	# Navigation
	[params.navigation]
		brand = "The Agency"
		services = "Services"
		portfolio = "Portfolio"
		about = "About"
		team = "Team"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "http://gohugo.io"
        name = "External link"
        weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Somos Cáprica"
		subtitle = "Diseño. Desarrollo. Creatividad. De otro planeta."
		buttonText = "Bienvenido"

		# Intro section
		[params.intro]
					enable = true
			title = "NOSOTROS"
			subtitle = "Cáprica es un planeta habitado por formas de vida complejas que se alimentan del trabajo bien hecho y de la satisfacción de sus clientes. Nuestros habitantes (Nosotros, los Cápriquers) tienen numerosas habilidades diseñando y desarrollando productos web, móvil, interactivos y de impresión."
			subtitle2 = "Estés en fase idea, en una etapa inicial, o en busca de un mayor desarrollo, te ayudaremos a establecer una visión global de tu producto. Combinamos creatividad, estrategia, diseño y desarrollo en un completo proceso para crear experiencias de usuario únicas."
			ending = "¡Está en nuestra sangre, somos de Cáprica!"
	# Services section
	[params.services]
        enable = true
		title = "¿Qué ofrecemos?"
		subtitle = "Nuestros conocimientos, nuestras amplias habilidades y la fantástica relación con nuestro planeta vecino 'Startup' nos hacen diferentes del resto. "

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-paint-brush"
                title = "DESARROLLO DE MARCA"
                description = "En Cáprica tenemos una amplia experiencia en el desarrollo y diseño de marca. Somos conscientes de que el logotipo es la identidad de una marca y queremos que brille. ¡Si hasta nuestra estrella se llama así!<br/>Nuestro equipo de diseñadores trabaja duro para encontrar la tipografía, el color y la forma perfectos para transmitir vuestro mensaje en forma de logotipo, ilustraciones, anuncios, etc... Y nuestros creativos tienen el mensaje idóneo para hacer de tu compañía la más cool de las redes.<br/>En nuestro planeta lo raro es no ser cool."
								skills = ["Naming", "Branding", "Diseño", "Ilustraciones", "Publicidad y Marketing creativo", "Escritura creativa"]
            [[params.services.row.list]]
                icon = "fa-user-md"
                title = "DISEÑO CENTRADO EN EL USUARIO"
                description = "Nuestra especie cuenta con más de 15 años de experiencia en el diseño y elaboración de interfaces usables tanto para web como para móvil. Comenzamos nuestro proceso de diseño con wireframes y pruebas de usuario, permitiéndonos realizar iteraciones rápidas y cambios incrementales a bajo coste."
								skills = ["User Research + Entrevistas", "A / B Testing", "Diseño de experiencia de usuario", "Wireframes + prototipos", "Diseño de interfaz de usuario"]
            [[params.services.row.list]]
                icon = "fa-building-o"
                title = "DESARROLLO FULL-STACK"
                description = """Aunque te parezca sorprendente, también somos desarrolladores full-stack que aplican metodologías ágiles demostrado que desarrollar en Ruby on Rails, Laravel, AngularJS, React y Sass es posible sin eternos tiempos de espera. Trabajamos en sprints de 2 semanas, publicando código con frecuencia y elaborando completos tests que minimizan los errores en la aplicación.

¡Somos de otro planeta! :D"""
								skills = ["Laravel / Ruby on Rails / nodeJS para desarrollo del lado del servidor", "Frameworks de JavaScript para desarrollo del lado del cliente", "Desarrollo modular basado en metodologías DRY (No Te Repitas / Don't Repeat Yourself)", "Test Driven Development (TDD o Desarrollo guiado por pruebas)", "Desarrollo móvil. Android, iOS y Windows Phone."]
	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
	[params.about]
        enable = true
		title = "About"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2009-2011"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "2.jpg"
			date = "March 2011"
			title = "An Agency is Born"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "3.jpg"
			date = "December 2012"
			title = "Our Humble Beginnings"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "4.jpg"
			date = "July 2014"
			title = "Phase Two Expansion"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


	# Team section
	[params.team]
        enable = true
		title = "Our amazing team"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde."

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "1.jpg"
			name = "Kay Garland"
			position = "Lead Designer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "2.jpg"
			name = "Larry Parker"
			position = "Lead Marketer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "3.jpg"
			name = "Diana Pertersen"
			position = "Lead Developer"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

	# Client section
    [params.clients_list]
        enable = true

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "envato.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "designmodo.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "themeforest.jpg"
    		link = "#"

    	[[params.clients]]
    		logo = "creative-market.jpg"
    		link = "#"


	# Contact section
	[params.contact]
        enable = true
		title = "Contact us"
		subtitle  = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "#"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "#"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
